version: 2.1
executors:
  node_image:
    docker:
      - image:  cimg/node:22.13.1-browsers

jobs:
  build:
    executor: node_image
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm run lint
      - run:
          command: npx playwright install --with-deps
      - run:
          command: npm run test
      - run:
          command: npm run build

workflows:
  build:
    jobs:
      - build


